name: Automation
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up cache
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check types
        run: yarn types

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up cache
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn exec biome -- ci

  build:
    name: Build generated files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up cache
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build generated files
        run: yarn build
      - name: Check for changes
        run: >
          if [ -z "$(git status --porcelain)" ];
          then
            echo "Generated files are up to date."
            exit 0
          else
            echo "Some files have not been regenerated recently. Please run 'yarn build' to fix this."
            echo "$(git status)"
            exit 1
          fi
